repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    # See: https://pre-commit.com/hooks.html
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.2
    hooks:
    -   id: pylint
