repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    # See: https://pre-commit.com/hooks.html
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
# Pre-commit has separate env where it installs and runs hooks, so they can be reused. This causes
# problems for hooks that require a state that is only present in your environment, e.g. pylint
# needs to access deps you installed in your venv.
# See: https://pre-commit.com/#repository-local-hooks
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
